NUMPY ARRAY OPERATION

In [2]:
import numpy as np 


In [ ]:
arr = np.array([1,2,3,3,4,5,6])
print(arr[2:4])
print(arr[-3])

arr_2d = np.array([[1,2,3]
               ,[4,5,6],
                [7,8,9]])
print(arr_2d[1,2])   # refer specific element 



[3 3]
4
6


sorting

In [19]:
unsorted = np.array([3,1,4,2,7,8,5,9])
print(np.sort(unsorted))

arr_2d_unsorted = np.array([[1,5],[3,6],[9,8]])
print(np.sort(arr_2d_unsorted,  axis = 1))

[1 2 3 4 5 7 8 9]
[[1 5]
 [3 6]
 [8 9]]


FILTERING

In [20]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_number = numbers[numbers%2 == 0]
print(even_number)

[2 4 6 8]


filter with mask

In [23]:
mask = numbers > 5 
print(numbers[mask])

[6 7 8 9]


Fancy indexing vs np.where()

In [38]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(numbers[where_result])

condition_array = np.where(numbers > 5, "true" , "false")
print(condition_array)


[1 3 5]
[6 7 8 9]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']


condition array

In [32]:
condition_array = np.where(numbers > 5)
print(condition_array)

(array([5, 6, 7, 8]),)


ADDING AND REMOVIND DATA 

In [45]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
combined = np.concatenate((arr1,arr2))
print(combined)

[ 1  2  3  4  5  6  7  8  9 10]


array compatibility

In [49]:

a = np.array([1,2,3])
b = np.array([6,7,8,7])
c = np.array([9,7,6])
print(a.shape == b.shape)

False


In [52]:
original = np.array ([[1,2],[3,4]])
new_row = np.array([4,5])
with_new_row = np.vstack((original,new_row))#combine new row 
print(original)
print(with_new_row)

new_col = np.array([[7] , [8]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [4 5]]
[[1 2 7]
 [3 4 8]]


In [53]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print(deleted)

[1 2 4 5]
