##NUMPY ARRAY AND BASICS 
LEARN ABOUT NUMPY 

In [1]:
import numpy as np

###creating array from lis

In [3]:

arr_1d = np.array([1,2,3,4,5])
print("1D array:", arr_1d)

arr_2d= np.array([[1,2,3], [4,,5,6]])
print("2D array:", arr_2d)

SyntaxError: invalid syntax (3409090347.py, line 4)

list vs numpy array

In [9]:
py_list = [1, 2 , 3]
print(py_list*2)

np_array = np.array([1,2,3])
print(np_array*2) #element wise multiplication

import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print(time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print(time.time() - start)


[1, 2, 3, 1, 2, 3]
[2 4 6]
0.12867474555969238
0.008809566497802734


creating array from scartch

In [16]:
zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((3,4))
print(ones)


full = np.full((2,2) , 6)
print(full)

random = np.random.random((3,4))
print(random)

sequence = np.arange(0, 10 , 2 )
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6 6]
 [6 6]]
[[0.35273761 0.64061305 0.06279867 0.88779009]
 [0.58140094 0.14284915 0.16445853 0.43607324]
 [0.48392809 0.01861036 0.09415938 0.16596655]]
[0 2 4 6 8]


###VECTOR , MATRIX AND TENSOR

In [20]:
vector = np.array([1,2,3])
print(vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print(matrix) 

tensor = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print(tensor)                    

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##array properties

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)#rows and colomn
print(arr.ndim)#gives dimension 
print(arr.size)#no. of elements
print(arr.dtype)#datatype




(2, 3)
2
6
int64


ARRAY RESHAPING

In [34]:
arr = np.arange(12)
print(arr)
reshaped = arr.reshape((3,4))
print(reshaped)

flattened = reshaped.flatten()
print(flattened)
#ravel = returns view instead of copy
raveled = reshaped.ravel()
print(raveled)

#transpose
transpose = reshaped.T
print(transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
